In [1]:
import os
os.chdir('..')

In [2]:
!pip install bs4

Requirement already satisfied: bs4 in ./.conda/lib/python3.11/site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in ./.conda/lib/python3.11/site-packages (from bs4) (4.13.4)
Requirement already satisfied: soupsieve>1.2 in ./.conda/lib/python3.11/site-packages (from beautifulsoup4->bs4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in ./.conda/lib/python3.11/site-packages (from beautifulsoup4->bs4) (4.14.1)

In [10]:
import pandas as pd
from bs4 import BeautifulSoup as BS
import re

In [4]:
data = pd.read_csv('./data_collecting/conversations.csv')
data

,Unnamed: 0,Unnamed: 0_res,uid_res,subject_res,from_res,in_reply_to_res,to_res,date_res,text_res,html_res,...,in_reply_to_req,to_req,date_req,text_req,html_req,flags_req,size_req,attachments_count_req,headers_req,msg_id
0,0,41,7791,Re: упд 304,tender@geekprom.ru,NaN,kristina.trifonova@rusal.com,2024-07-04 11:29:00,NaN,"<div>У нас с вами обмен по ЭДО, выгруженный до...",...,NaN,tender@geekprom.ru,2024-07-04 06:51:08,Добрый день!\r\n\r\nПришлите пожалуйста скан п...,"<html xmlns:v=""urn:schemas-microsoft-com:vml"" ...","\Seen, \Answered",110572,2,{'received': ('from mail-collectors-production...,<2756ec146bd14e7f91b7488c7916b0ee@rusal.com>
1,1,44,8066,Re: Акт сверки за 2 квартал и 1 полугодие 2024,tender@geekprom.ru,NaN,dolgushina@yargeo.novatek.ru,2024-07-10 13:22:47,NaN,"<div>Добрый день, Валентина Леонидовна!</div><...",...,NaN,tender@geekprom.ru,2024-07-10 03:56:16,Доброе утро!\r\n\r\nНаправляю в Ваш адрес Акты...,"<html xmlns:v=""urn:schemas-microsoft-com:vml"" ...","\Seen, \Answered",272167,3,{'received': ('from mail-collectors-production...,<edc1c56805d34253a5a805262305a49d@yargeo.novat...
2,2,49,8750,Re: Заказ,info@geekprom.ru,NaN,gudkovaaa@layta.ru,2024-07-25 09:15:39,NaN,"<div>Альбина, доброго дня.</div><div>Счет с ук...",...,NaN,info@geekprom.ru,2024-07-25 05:44:18,Добрый день!\r\nПро8шу счет и сроки:\r\nАналит...,"<html xmlns:v=""urn:schemas-microsoft-com:vml"" ...","\Seen, \Answered, encrypted, system_hamon",24476,0,{'received': ('from postback2a.mail.yandex.net...,<6844fa16f7b945688d37ec1c6fb3bb4d@srvsrt01mlp0...
3,3,124,13563,Re: Сообщение с сайта dv-expert.ru от tender@g...,tender@geekprom.ru,NaN,114@dv-expert.org,2024-10-07 11:58:05,NaN,<div>Добрый день!</div><div>нет не выиграли</d...,...,NaN,tender@geekprom.ru,2024-10-06 14:28:27,"Добрый день!\r\n\r\nПодскажите, так понимаю вы...","<html xmlns:v=""urn:schemas-microsoft-com:vml"" ...","\Seen, \Answered",46889,2,{'received': ('from mail-collectors-production...,<00d601db17e2$dd377ad0$97a67070$@dv-expert.org>
4,4,146,14543,Re: Акт сверки,tender@geekprom.ru,NaN,alekseeva@yargeo.novatek.ru,2024-10-17 16:19:53,NaN,<div>Акт сверки во вложении</div><div> </div><...,...,NaN,tender@geekprom.ru,2024-10-17 03:14:59,Доброе утро!\r\nПрошу подписать акт сверки.\r\...,"<html xmlns:v=""urn:schemas-microsoft-com:vml"" ...","\Seen, \Answered",254298,3,{'received': ('from mail-collectors-production...,<45cd46bd784d4fabae3b7670bb87cefa@yargeo.novat...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22836,23531,49457,93507,Re: Заявка,info@geekprom.ru,NaN,inteh-rm@yandex.ru,2025-08-22 15:17:15,NaN,<div>Здравствуйте!</div><div>Счет на оплату во...,...,NaN,info@geekprom.ru,2025-08-22 11:37:58,NaN,<div>Здравствуйте.</div><div>Сделайте счет на ...,"\Seen, \Answered, \Recent, encrypted, system_h...",16649,0,{'received': ('from postback25d.mail.yandex.ne...,<56961755851864@mail.yandex.ru>
22837,23533,49463,93514,Отгрузка,info@geekprom.ru,NaN,bazyaka_oleg@mail.ru,2025-08-22 16:06:38,NaN,"<div>Олег,</div><div><div style=""background-co...",...,NaN,info@geekprom.ru,2025-08-22 15:30:22,"оплатил, когда ждать доставку?\r\n\r\n> 22 авг...","<html><head><meta http-equiv=""content-type"" co...","\Seen, \Answered, \Recent, encrypted, system_h...",40058,0,{'received': ('from postback7d.mail.yandex.net...,<301D3850-56DA-462F-919C-1B55CC349553@mail.ru>
22838,23534,49468,93519,Re: Заявка,info@geekprom.ru,NaN,elektrobest@yandex.ru,2025-08-22 16:41:07,NaN,<div>Здравствуйте!</div><div> </div><div>Высыл...,...,NaN,info@geekprom.ru,2025-08-22 16:10:19,NaN,<div>Только количество 1шт!</div><div><br /></...,"\Seen, \Answered, \Recent, encrypted, system_h...",15814,0,{'received': ('from postback13d.mail.yandex.ne...,<572101755868209@mail.yandex.ru>
22839,23535,49469,93522,Re: Электрохимические ячейки Southland Sensing,info@geekprom.ru,NaN,o.oleynik@ngco.pro,2025-08-22 17:15:15,NaN,"<div>Здравствуйте, Оксана!</div><div> </div><d...",...,NaN,o.oleynik@ngco.pro,2025-08-21 08:25:32,Добрый день!\r\n\r\nПросим направить КП на пос...,"<html xmlns:v=""urn:schemas-microsoft-com:vml"" ...","\Seen, \Answered, \Recent, encrypted",47123,2,{'received': ('from postback29a.mail.yandex.ne...,<5a7d8a8b1dc340b78614deb0c6c09c9e@ngco.pro>
22840,23536,49470,93523,Re: ЗАКАЗ,info@geekprom.ru,NaN,marinevl@mail.ru,2025-08-22 17:20:21,NaN,<div>вчера приборы выехали. Вот номер отслежив...,...,"('marinevl@mail.ru',)",info@geekprom.ru,2025-08-22 14:23:51,\nДобрый день!\nСпасибо\nПодскажите пожалуйста...,\n<HTML><BODY><div><div>Добрый день!</div><div...,"\Seen, \Answered, \Recent, encrypted, system_h...",49878,0,{'received': ('from postback23a.mail.yandex.ne...,<1755861831.730675107@f733.i.mail.ru>

In [5]:
print(data.html_res[data['html_res'].notna()].shape[0])
data.html_req[data['html_req'].notna()].shape[0]

22839

21921

In [18]:
def remove_html_tags(html_text):
    if pd.notna(html_text):
        html = BS(html_text, 'html.parser')
        return html.get_text(separator=' ')
    return pd.NA
    
def clean_text(text):
    if pd.notna(text):
        text = re.sub(r'[\r\n\t]+', ' ', text)
        text = re.sub(r'[ ]{2,}', ' ', text)
        text = text.strip()
        return text
    return pd.NA

In [19]:
cleaned_html_req = data.html_req.apply(remove_html_tags).apply(clean_text)
cleaned_html_req

0        Добрый день!   Пришлите пожалуйста скан подпис...
1        Доброе утро!   Направляю в Ваш адрес Акты свер...
2        Добрый день! Про8шу счет и сроки: Аналитприбор...
3        Добрый день! Подскажите, так понимаю вы не заб...
4        Доброе утро! Прошу подписать акт сверки. Скан ...
                               ...
22836    Здравствуйте. Сделайте счет на оплату 2шт.   -...
22837    оплатил, когда ждать доставку? 22 авг. 2025 г....
22838    Только количество 1шт! --  С Уважением, ООО "Э...
22839    Добрый день!   Просим направить КП на поставку...
22840    Добрый день! Спасибо Подскажите пожалуйста, ещ...
Name: html_req, Length: 22841, dtype: object

In [ ]:
cleaned_html_req[22839]

'Добрый день! \xa0 Просим направить КП на поставку TO2-1x PPM Oxygen Sensor -аналог Teledyne B2C - 4 шт. В КП просим указать наличие/сроки поставки и условия оплаты. \xa0 Карточка компании во вложении. \xa0 С уважением, \xa0 Оксана Олейник | Oksana Oleynik Ведущий специалист по логистике | Key Logistics Specialist 8\xa0800\xa0250 8\xa0052 | +7 (985) 893 39 77 \xa0 o . oleynik @ ngco . pro | www . ngco . pro'

In [22]:
cleaned_html_res = data.html_res.apply(remove_html_tags).apply(clean_text)
cleaned_html_res

0        У нас с вами обмен по ЭДО, выгруженный докумен...
1        Добрый день, Валентина Леонидовна!   Подписанн...
2        Альбина, доброго дня. Счет с указанием сроков ...
3        Добрый день! нет не выиграли   --  С уважением...
4        Акт сверки во вложении   --  С уважением, Гром...
                               ...
22836    Здравствуйте! Счет на оплату во вложении.   --...
22837    Олег, продукция по Вашему заказу отправлена ТК...
22838    Здравствуйте!   Высылаю счет.   Он действует 2...
22839    Здравствуйте, Оксана!   Высылаю счет, согласно...
22840    вчера приборы выехали. Вот номер отслеживания:...
Name: html_res, Length: 22841, dtype: object

In [33]:
data[['attachments_count_req', 'uid_req']][data['attachments_count_req'].apply( lambda x: int(x)) > 0]

       attachments_count_req  uid_req
0                          2     5918
1                          3     6181
3                          2    10075
4                          3    10846
5                          2    11469
...                      ...      ...
22827                      1    32735
22828                      1    32737
22829                      5    32738
22835                      2    32753
22839                      2    32765

[12433 rows x 2 columns]